apiVersion: v1
kind: Pod
metadata:
  name: database-pod
  labels:
    app: database
spec:
  containers:
  - image: cloudapps:db
    name: database-container
    imagePullPolicy: IfNotPresent
    ports:
      - containerPort: 27017
        name: http
        protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: database-service
  labels:
    app: database
spec:
  type: NodePort
  selector:
    app: database
  ports:
  - name: http
    protocol: TCP
    port: 27017
    targetPort: 27017
    nodePort: 30020