apiVersion: v1
kind: Pod
metadata:
  name: database-pod
  labels:
    app: database
spec:
  containers:
  - image: mysql
    name: database-container
    imagePullPolicy: IfNotPresent
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: zaq1@WSX
    ports:
      - containerPort: 3306
        name: http
        protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: database-service
  labels:
    app: database
spec:
  type: NodePort
  selector:
    app: database
  ports:
  - name: http
    protocol: TCP
    port: 3306
    targetPort: 3306
    nodePort: 30020