apiVersion: v1
kind: Pod
metadata:
  name: front-pod
  labels:
    app: frontend
spec:
  containers:
  - image: production_frontend
    name: frontend-container
    imagePullPolicy: IfNotPresent
    env:
      - name: REACT_APP_API_URL
        value: http://localhost:5000
    ports:
      - containerPort: 5173
        name: http
        protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  labels:
    app: frontend
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
  - name: http
    protocol: TCP
    port: 5173
    targetPort: 5173
    nodePort: 30000