apiVersion: v1
kind: Pod
metadata:
  name: frontend-pod
  labels:
    app: frontend
spec:
  containers:
  - image: production_frontend
    name: frontend-container
    imagePullPolicy: IfNotPresent
    env:
      - name: REACT_APP_API_URL
        value: backend-service:5000
    ports:
      - containerPort: 80
        name: http
        protocol: TCP
    livenessProbe:
      httpGet:
        path: /index.html
        port: http
      initialDelaySeconds: 15
      timeoutSeconds: 1
      periodSeconds: 10
      failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  labels:
    app: frontend
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30000