apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
nodes:
  - extraPortMappings:
    - containerPort: 30020
      hostPort: 3306
    - containerPort: 30010
      hostPort: 5000
    - containerPort: 30000
      hostPort: 8080